### ISSUE TITLE
ValueSet / ValueSetEntry inconsistency?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4runtime#113]
ValueSet have only a single `bitwidth` field, but a ValueSetEntry has a `repeated FieldMatch match = 2;` that enables specifying multiple fields.  Is the plan that implementations of P4Runtime v1.0 spec will restrict themselves to a single `match` field in each ValueSetEntry?  Something else?

**Comment by antoninbas** [comment]
The repeated field in ValueSetEntry is to specify the complete list of entries in the Value Set. Implementations don't have to limit themselves to a single match in each ValueSetEntry, however they are limited to storing simple bitstring types in a Value Set.
So `ValueSet<bit<8> >` and `ValueSet<bit<24> >` are supported but `ValueSet<tuple<bit<8>, bit<24> > >` is not (although a workaround is to store 8 + 24 = 32-bit values directly into the set).
This is the same limitation as on table match keys (because they use the same `FieldMatch` Protobuf message, which doesn't use `P4Data`).

**Comment by jafingerhut** [comment]
Ah, got it now.  Somehow I missed that on my reading about ValueSetEntry, that it adds the entire sequence of .  Looks all good then.

I would bet that most readers would infer this on their own, but I would recommend that the section on ValueSetEntry explicitly mention that the order of the `repeated FieldMatch match = 2;` sequence _is_ significant, and must be preserved by the server when it programs the data plane.

**Comment by jafingerhut** [comment]
OK, thinking more, I take back my previous comment that the sequence is signfiicant -- it is not.  An unordered set is fine here, since it is strictly a logical OR for packets being matched against entries of the set.

I am closing this issue, since I cannot think of any changes to the spec for it.
