### ISSUE TITLE
What happens if an action profile member weight is 0 (default value)?

### ISSUE THREAD

**Issue by antoninbas** [p4lang/p4runtime#166]
Should the server return an error or treat it as 1?

**Comment by jafingerhut** [comment]
Would having the server treat it as 1 violate the read-write symmetry principle?  That symmetry principle isn't an ironclad law or anything like that, I know, but was curious what the answer to the question is, and whether that might inform a good answer to your original question.

**Comment by ccascone** [comment]
Reasons why the server should treat 0 as 1:
* Smaller messages/protocol efficiency when programming ECMP-like groups (as opposed to WCMP)

Reasons why the server should NOT treat 0 as 1:
* It makes the spec more ambiguous
* 0 could have its own meaning. For example, to temporarily "deactivate" a member from a group, although I cannot think of any good reason why one should prefer this approach instead of removing the member from the group.
* Otherwise we get to answer to @jafingerhut question about symmetry :D

**Comment by stefanheule** [comment]
Symmetry should actually be a strong reason to not treat 0 as 1.  Otherwise the target will have to remember if the programming of a group of weight 1 was done using 0 or 1.  I suggest we go with 0 being an error, and saying so explicitly.

**Comment by antoninbas** [comment]
These all sound like good points to me. Thanks for the quick feedback. I'll update the spec to state that 0 is not allowed.
