### ISSUE TITLE
Should server auto-replace action selector group max_size of 0 with a non-0 value?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4runtime#168]
There are two places I have found where it says this in the section "Action Profile Group Programming":

"If the `max size` is not known at group creation-time, the client may
  leave this field unset (default value 0), in which case the static
  `max_group_size` value will be used and the group will be able to include up
  to `max_group_size` weighted member entries."

and later when describing the `INSERT` operation:

"If the client does
  not set `max_size`, the default value (0) implies that the statically-defined
  maximum size should be used for this group."

It seems like doing this could break read-write symmetry, similar to issue https://github.com/p4lang/p4runtime/issues/166

If so, and we want to avoid that, perhaps a `max_size` that is 0 should be either left at 0, or an error?  An error seems reasonable, unless there is a known use case for creating a group that can never have members added to it.

**Comment by stefanheule** [comment]
I would be in favor of also not allowing silent mappings from 0 to max_size here, for the same reasons as in #166: Now a target would need to remember if 0 or max_size was used to indicate max_size.  If the client wants max_size, it can just use max_size.

If 0 should be allowed or not is less important to me.  I can't think of a usecase, but I can't think of any harm either.

**Comment by antoninbas** [comment]
I think we need a way to say "as large as the target can go", which was originally a request from Samar. Using 0 was a way to achieve this.

Now maybe this should only be possible if the static max size (`max_group_size`) is also 0, in which case we have `max_size == max_group_size` anyway.

So I would suggest the following changes:
 * Define the `@max_group_size` P4 annotation used to set `max_group_size` in P4Info. It's currently missing from the spec.
 * In absence of this annotation, `max_group_size` will default to 0, which means "as large as the target can go". P4Info being target-independent, `max_group_size` must be 0, now whatever the target can support.
 * The server needs to enforce the following:

    * `max_size == 0 => max_group_size == 0`
    * `max_group_size > 0 => (max_size <= max_group_size)
    * If `max_group_size == 0`, the client can choose any value `>= 0` for `max_size`. If the value is not supported by the target, it must return an error.

Therefore we don't have 2 ways of expressing the "same thing" (even though I'm not sure it's technically the same thing, despite what the spec implies) which should make RW symmetry easier.

**Comment by jafingerhut** [comment]
It seems a little bit odd to have action selector max_group_size be the one parameter of a P4Info program that is allowed to vary from one target to another for the same P4 program, when even the table sizes are specified in the P4 source code and thus identical across targets.

Or perhaps table sizes are also planned to have some encoding in the P4Info file to indicate "as large as the target can go"?

If that seems OK to people to let this parameter vary across targets by storing max_group_size==0 in the P4Info file, should there be a way for a client to read at runtime, independently for each ActionSelector instance, what that particular device's `max_group_size` value actually is?

**Comment by antoninbas** [comment]
I don't think P4Info should ever be different across targets. It should reflect what's in the P4. Since `max_group_size` (unlike `size`) is not an argument to the PSA `ActionSelector` extern constructor, yet this information is still useful, we rely on an annotation. I can't think of a good reason to make this annotation mandatory, so default'ing to 0 seems logical to me. The only way to interpret the absence of annotation IMO is as "try to accommodate all the client's requests, fail if you can't because the group is too large". If the annotation is present, we will use the provided value and the P4Info will include the same value for all targets.

If you don't like the solution I proposed in my previous comment, we can also require that `max_size > 0`. Now the client must always provide a size when creating the group, and the target will reject it if it's too large to be supported or if it is `> max_group_size` (if provided). I remember Samar not being a fan of this solution, but I'm personally not opposed to it and @stefanheule can let us know what he thinks.

As for the ability to query capabilities, this entire topic has been postponed to after 1.0.0. There is simply no mechanism in P4Runtime at the moment to query object properties.

**Comment by antoninbas** [comment]
For reference, this is taken from the minutes of a P4 API WG meting (May 2018):

> Decision: add annotation or constructor parameter to PSA.ActionSelector to specify the maximum size (i.e. sum of weights for all members belonging to the group) for any group; keep max_size (max size of group being created) in ActionProfileGroup in case some targets can leverage it or require it to use resources optimally; controller may set max_size to 0 if size is unknown at group creation time; max_size must be <= than the compile-time value

**Comment by stefanheule** [comment]
The proposal @antoninbas made in the third comment sounds good to me.

**Comment by jafingerhut** [comment]
The 2nd and 3rd bullet points copied below from Antonin's proposal seem to contradict each other:

"The server needs to enforce the following:
+ max_size == 0 => max_group_size == 0
+ max_group_size > 0 => (max_size <= max_group_size)
+ If max_group_size == 0, the client can choose any value >= 0 for max_size. If the value is >0 and is not supported by the target, it must return an error."

The P4Runtime server should know the following values, independently for each action selector:
+ max_group_size_from_p4info, which may be 0
+ max_group_size_of_device, which must be > 0

Perhaps the enforcement rules of the server could be written this way?
+ 0 <= max_size <= max_group_size_of_device, or else server returns an error
+ max_size == 0 => max_group_size_from_p4info == 0, and actual group size used will then be max_group_size_of_device
+ max_size > 0 => the actual group size used will then be max_size, unless there is an error such as violating (max_size <= max_group_size_of_device), or hardware resources are exhausted, etc.

**Comment by antoninbas** [comment]
@jafingerhut I don't think there is a contradiction between the 2nd and 3rd bullet point since the 2nd bullet point is a rule for `max_group_size > 0` while the 3rd is an orthogonal rule for `max_group_size == 0`. For the 3rd bullet point, in "If the value is > 0", "value" refers to `max_size`, not the P4Info size (`max_group_size`).

That being said I feel like we are mostly in agreement. As far as I can tell, the only different is that I included an extra rule: `max_group_size_from_p4info != 0 => max_size <= max_group_size_from_p4info`. Let me know if you have an issue with that.

**Comment by jafingerhut** [comment]
Sorry, yes, I made a mistake saying there was a contradiction there.  Ugh.  I think we are in agreement, too.
