### ISSUE TITLE
Resetting counters of const table entries

### ISSUE THREAD

**Issue by konne-google** [p4lang/p4runtime#232]
How do I reset the counters of a const table entry? It sounds like P4RT doesn't support this. If so, is there a reason why? Can we support it. The relevant spec quotes:

"The only write updates which are allowed for constant tables are MODIFY operations on the default action"

"we assume that constant tables cannot be assigned direct resources"

**Comment by konne-google** [comment]
Andy & Antonin, do you remember why this is what we chose?

**Comment by antoninbas** [comment]
We had a very short discussion about it there: https://github.com/p4lang/p4-spec/issues/723
We can revisit the topic at the next WG meeting. I think the reason why we chose this is that 1) we didn't have a use case at the time (but it seems it is no longer the case since you are trying to use a direct counter with a constant table), and 2) it seemed non-trivial to define good semantics for reading / writing direct resource entries using the `TableEntry` message (`DirectCounterEntry` and `DirectMeterEntry` are more straightforward).

The current spec states that

> The `TableEntry` `action` field must be set for every `INSERT` and `MODIFY` update, except when resetting the default entry

so when trying to reset a counter with a `MODIFY` update using a `TableEntry` message, the client would need to provide the full & correct action specification (based on the P4 table declaration).

Personally, I don't see any particular issue with supporting resetting the counters of a const table using the `DirectCounterEntry`. If we want to support `TableEntry` messages as well, it may be trickier.

**Comment by antoninbas** [comment]
This was discussed at the 08/28/2019 P4 API WG meeting (https://docs.google.com/document/d/1qzeAnKDDOIgBzq3sLS1C1CacunTtrV5x5T5xPXUFRGM/edit#heading=h.1luy7m2zeqb), and we decided to include support for this in P4Runtime v1.1.0.
