### ISSUE TITLE
Using strings for role

### ISSUE THREAD

**Issue by konne88** [p4lang/p4runtime#344]
Could we add string based roles to P4Runtime. The idea is that a string is much more readable (e.g. "tunnel manager") than to use an id (e.g. 1).

```
message WriteRequest {
  uint64 device_id = 1;
  uint64 role_id = 2;          // deprecated
  string role_name = 6;     // new
  Uint128 election_id = 3;

// ...

message SetForwardingPipelineConfigRequest {
  // ...
  uint64 device_id = 1;
  uint64 role_id = 2;          // deprecated
  string role_name = 6;     // new
  Uint128 election_id = 3;
  Action action = 4;
  ForwardingPipelineConfig config = 5;
}
```

**Comment by konne88** [comment]
@antoninbas @stefanheule 
What do you think about this idea? If this seems reasonable, I'm happy to send out the PR to change the spec.

**Comment by stefanheule** [comment]
Seems very reasonable, I'm a big fan of making things easier to debug/understand. If someone still prefers an integer as the role, they can still do that by encoding it as a byte-string (or even a regular string), so this is not limiting any prior usecases either.

**Comment by jafingerhut** [comment]
It appears that performance concerns are less of an issue for the role, since it is only once per WriteRequest as probably the most frequent message it appears in.

This might tread into "number of angels that can dance on the head of a pin" kinds of discussion, but does this mean that a P4Runtime server must continue to support role_id until and unless it upgrades to a version of P4Runtime API that explicitly breaks backwards compatibility and drops role_id completely?

**Comment by konne88** [comment]
Let's discuss this in tomorrow's meeting. In general, the way we've handled this is by returning UNIMPLEMENTED for any feature that we don't support (of which there are many).
