### ISSUE TITLE
Can a multicast group id / a clone session id / a replica id be 0?

### ISSUE THREAD

**Issue by antoninbas** [p4lang/p4runtime#44]
Usually in P4Runtime, 0 is an invalid id. Are things different for multicast group id / clone session id / replica id? Unlike an action profile member id for example (but much like a port id?), these ids map directly to P4 metadata fields. We need to make a decision and include it in the specification.

I think these ids are different from from other P4Runtime ids (e.g. action profile member id) which never leave the realm of the control-plane. They are also different from port ids IMO, since I would expect most targets to support a linear sequence of multicast group ids (for example) in the range `[0, 2^W[` and we may not want to worry about mapping / translation like we did for ports.

**Comment by jafingerhut** [comment]
Minor note: The PSA spec right now points out that a target data plane might support multicast group ids that aren't a power-of-2 sized range.  It isn't the most common thing in the world for hardware to do such things, but it is possible to create hardware tables whose number of entries isn't a power of 2, e.g. even if the physical hardware tables have power-of-2 restrictions, it is less ASIC die area to implement a 16K-entry SRAM plus an 8K-entry SRAM if you only want/need 24K entries, vs. two 16K-entry SRAMs.

The PSA spec I think mentions that there should probably be a control plane API mechanism for a controller to determine a target device's range of values supported by a target for such things, but if I wrote that, I didn't know what P4Runtime API plans were at the time there.   This perhaps falls under the more general category of querying for what features/extensions/capabilities a device has.

**Comment by antoninbas** [comment]
This was discussed at the 09/12/2018 P4 API WG meeting: https://docs.google.com/document/d/1yMOzmIOJo4_q2yCc1_eGcniag-Q7w2F_f3kKu9JB64c/edit#heading=h.oqpj7v8wbl65
No one expressed a strong opinion on this. @jafingerhut noted that the PSA spec actually states that 0 is not a valid dataplane multicast group id value.
It is unclear to me what the correct solution is. For consistency across the P4Runtime specification, maybe we should
 * specify that 0 is always an invalid *control-plane* id for multicast (replica id too?), cloning, Qos, ...
 * mention in the spec that these ids can be translated (just like port ids) and that it is therefore possible to have 0 as a dataplane id (save for multicast groups?) even though the corresponding control-plane id wouldn't be 0. Is the translation of multicast group ids / clone session ids / ... more subtle than port translation?

**Comment by jafingerhut** [comment]
I will make a list of all 7 types defined in the PSA v1.0 spec below, just to see there are any surprises for any of them.  No changes have been made since v1.0 of the spec that affects any of this.

Let me first make a poor attempt at being brief in my recommendations:
+ PortId_t - Make 0 invalid in control plane, PSA says nothing about 0 being special in data plane so should be assumed valid for some PSA devices.  We already plan numerical translation here.
+ MulticastGroup_t - Make 0 invalid in control plane, PSA 0 cannot ever be used to cause multicast replication, only to specify "no multicast replication for this packet".  No need for numerical translation here that I can see.
+ CloneSessionId_t - Make 0 invalid in the control plane.  PSA says nothing about 0 being special in data plane so 0 should be assumed valid for some PSA devices.  Numerical translation seems useful if we expect some PSA devices to have few valid clone session ids (maybe as low as 4 or 8?) and we don't want to waste using id 0 in the data plane.
+ ClassOfService_t - Similar to CloneSessionId_t.
+ PacketLength_t - 0 should be valid in the control plane.  Recommend never doing numeric translation on values of this type.
+ EgressInstance_t - Make 0 invalid in the control plane if you want.  PSA says nothing about 0 being special in data plane so 0 should be assumed valid for some PSA devices.  Given that this value will probably be 10 or more bits in most data planes, wasting one seems insignificant, and numerical translation seems more likely to be confusing than helpful.
+ Timestamp_t - 0 is normal in the data plane.  Not clear whether there is a benefit to 0 being invalid in the control plane.  Numeric translation may be useful, but hasn't been discussed much yet.

Below are a few more gory details, only for the morbidly interested :-)

+ PortId_t - I have nothing more to add to the above.
+ MulticastGroup_t - For PSA data planes, it is reasonable while processing a packet to assign a value of 0 to the `multicast_group` metadata field, and in fact that is its initial value.  0 cannot in the data plane correspond to a multicast group on which to perform packet replication, because PSA in the data plane defines 0 to encode the decision of "I don't want to do multicast replication for this packet".  I suspect in many data path implementations this means there could be a hardware table somewhere indexed by the data path multicast_group value, and entry 0 will never be accessed.  I expect many data plane implementations to have thousands of multicast group ids, so wasting one entry is insignificant.
+ CloneSessionId_t - PSA does not define 0 to be special for clone session ids, so data plane implementations are free to use it as a valid clone session id if they want.  I would expect that many data plane implementations would have relatively few distinct clone sessions, e.g. maybe on the order of 4 to 16.  Thus leaving one of them unused in the data plane may be a bigger stress on this possibly scarce resource.  Remapping this value between control plane and data plane could be as simple as one of: (a) control plane value=data plane value+1, or (b) control plane value=(data plane value == 0) ? (MAX_DATA_PLANE_VALUE+1) : (data plane value)
+ ClassOfService_t - Similar to CloneSessionId_t.
+ PacketLength_t - I can't think of a reason why a data plane would ever need to represent a length of 0 bytes for an entire packet.  However, this type might be considered useful for representing lengths of _parts_ of a packet, too, e.g. the length of the payload, and in such cases 0 is a reasonable value.  I don't know if there are any difficulties in allowing 0 as a normal value for values of this type, but if there are no difficulties in doing so, it seems best to allow it.   Numerical translation of this value seems likely to lead to confusion, for no gain.
+ EgressInstance_t - The PSA says in the data plane that this value will be 0 for non-multicasted packets, but I think it is reasonable for some multicast-replicated packets to also have 0 for this value, since the packet_path value can be used to distinguish which packets were multicast-replicated vs. not, before ever examining the `instance` metadata field of a packet.  That said, I expect this value will typically have 10 bits or more in data paths, so wasting 0 in the data plane seems insignificant.  Numerical translation of this value between control and data planes seems  likely to lead to confusion, for no gain.
+ Timestamp_t - 0 is a perfectly normal value in the data plane - the data plane value is expected to wrap around during normal operation of the device.  Whether there is numeric translation between data plane and control plane has been mentioned as a possibility, but I am not aware of anyone proposing details in this area.  It hasn't been a high priority yet, I expect.
